// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
  ];
  late final Shape0 localRecordings = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'genre_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subcategory_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_5(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'duration_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_size_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'format',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'m4a\''),
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_file_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'upload_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'local\''),
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gcs_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cleaning_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'none\''),
    );
i1.GeneratedColumn<DateTime> _column_13(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'recorded_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_14(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      defaultValue: const CustomExpression(
        'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
      ),
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'retry_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<DateTime> _column_16(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_retry_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'register_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
  ];
  late final Shape3 localRecordings = Shape3(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'resumable_session_uri',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'uploaded_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
  ];
  late final Shape4 localRecordings = Shape4(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'md5_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
  ];
  late final Shape5 localRecordings = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
        _column_25,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
}

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
  ];
  late final Shape6 localRecordings = Shape6(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
        _column_25,
        _column_19,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localStorytellers = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'storyteller_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get age =>
      columnsByName['age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dialect =>
      columnsByName['dialect']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get externalAcceptanceConfirmed =>
      columnsByName['external_acceptance_confirmed']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sex',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'age',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dialect',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_32(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'external_acceptance_confirmed',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("external_acceptance_confirmed" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<DateTime> _column_33(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
  ];
  late final Shape6 localRecordings = Shape6(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
        _column_25,
        _column_19,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localStorytellers = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastCheckpointAt =>
      columnsByName['last_checkpoint_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalDurationSeconds =>
      columnsByName['total_duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get segmentPathsJson =>
      columnsByName['segment_paths_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isPaused =>
      columnsByName['is_paused']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get lastSegmentIndex =>
      columnsByName['last_segment_index']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<DateTime> _column_34(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_35(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_checkpoint_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'active\''),
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_duration_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'segment_paths_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<bool> _column_39(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_paused',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_paused" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_segment_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('-1'),
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
  ];
  late final Shape9 localRecordings = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
        _column_25,
        _column_19,
        _column_26,
        _column_27,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localStorytellers = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryGenreId =>
      columnsByName['secondary_genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondarySubcategoryId =>
      columnsByName['secondary_subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryRegisterId =>
      columnsByName['secondary_register_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secondary_genre_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secondary_subcategory_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secondary_register_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
  ];
  late final Shape10 localRecordings = Shape10(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_23,
        _column_24,
        _column_25,
        _column_19,
        _column_26,
        _column_27,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localStorytellers = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryGenreId =>
      columnsByName['secondary_genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondarySubcategoryId =>
      columnsByName['secondary_subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryRegisterId =>
      columnsByName['secondary_register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get splitFromId =>
      columnsByName['split_from_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get splitIndex =>
      columnsByName['split_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get splitSegmentCount =>
      columnsByName['split_segment_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'split_from_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'split_index',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'split_segment_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
  ];
  late final Shape10 localRecordings = Shape10(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_19,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_17,
        _column_41,
        _column_42,
        _column_43,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_23,
        _column_24,
        _column_25,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 localStorytellers = Shape11(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
        _column_10,
        _column_47,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get age =>
      columnsByName['age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dialect =>
      columnsByName['dialect']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get externalAcceptanceConfirmed =>
      columnsByName['external_acceptance_confirmed']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sync_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'synced\''),
    );

final class Schema11 extends i0.VersionedSchema {
  Schema11({required super.database}) : super(version: 11);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
    idxRecordingsProjectRecorded,
    idxRecordingsStatusRecorded,
    idxRecordingsServerId,
    idxRecordingsStorytellerId,
    idxStorytellersProjectId,
  ];
  late final Shape10 localRecordings = Shape10(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_19,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_17,
        _column_41,
        _column_42,
        _column_43,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_23,
        _column_24,
        _column_25,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 localStorytellers = Shape11(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
        _column_10,
        _column_47,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxRecordingsProjectRecorded = i1.Index(
    'idx_recordings_project_recorded',
    'CREATE INDEX idx_recordings_project_recorded ON local_recordings (project_id, recorded_at)',
  );
  final i1.Index idxRecordingsStatusRecorded = i1.Index(
    'idx_recordings_status_recorded',
    'CREATE INDEX idx_recordings_status_recorded ON local_recordings (upload_status, recorded_at)',
  );
  final i1.Index idxRecordingsServerId = i1.Index(
    'idx_recordings_server_id',
    'CREATE INDEX idx_recordings_server_id ON local_recordings (server_id)',
  );
  final i1.Index idxRecordingsStorytellerId = i1.Index(
    'idx_recordings_storyteller_id',
    'CREATE INDEX idx_recordings_storyteller_id ON local_recordings (storyteller_id)',
  );
  final i1.Index idxStorytellersProjectId = i1.Index(
    'idx_storytellers_project_id',
    'CREATE INDEX idx_storytellers_project_id ON local_storytellers (project_id)',
  );
}

final class Schema12 extends i0.VersionedSchema {
  Schema12({required super.database}) : super(version: 12);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
    idxRecordingsProjectRecorded,
    idxRecordingsStatusRecorded,
    idxRecordingsServerId,
    idxRecordingsStorytellerId,
    idxStorytellersProjectId,
  ];
  late final Shape12 localRecordings = Shape12(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_19,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_17,
        _column_41,
        _column_42,
        _column_43,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_23,
        _column_24,
        _column_25,
        _column_44,
        _column_45,
        _column_46,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 localStorytellers = Shape11(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
        _column_10,
        _column_47,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxRecordingsProjectRecorded = i1.Index(
    'idx_recordings_project_recorded',
    'CREATE INDEX idx_recordings_project_recorded ON local_recordings (project_id, recorded_at)',
  );
  final i1.Index idxRecordingsStatusRecorded = i1.Index(
    'idx_recordings_status_recorded',
    'CREATE INDEX idx_recordings_status_recorded ON local_recordings (upload_status, recorded_at)',
  );
  final i1.Index idxRecordingsServerId = i1.Index(
    'idx_recordings_server_id',
    'CREATE INDEX idx_recordings_server_id ON local_recordings (server_id)',
  );
  final i1.Index idxRecordingsStorytellerId = i1.Index(
    'idx_recordings_storyteller_id',
    'CREATE INDEX idx_recordings_storyteller_id ON local_recordings (storyteller_id)',
  );
  final i1.Index idxStorytellersProjectId = i1.Index(
    'idx_storytellers_project_id',
    'CREATE INDEX idx_storytellers_project_id ON local_storytellers (project_id)',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryGenreId =>
      columnsByName['secondary_genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondarySubcategoryId =>
      columnsByName['secondary_subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryRegisterId =>
      columnsByName['secondary_register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get splitFromId =>
      columnsByName['split_from_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get splitIndex =>
      columnsByName['split_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get splitSegmentCount =>
      columnsByName['split_segment_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reviewFlagsJson =>
      columnsByName['review_flags_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'review_flags_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'[]\''),
    );

final class Schema13 extends i0.VersionedSchema {
  Schema13({required super.database}) : super(version: 13);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
    idxRecordingsProjectRecorded,
    idxRecordingsStatusRecorded,
    idxRecordingsServerId,
    idxRecordingsStorytellerId,
    idxStorytellersProjectId,
  ];
  late final Shape13 localRecordings = Shape13(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_19,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_17,
        _column_41,
        _column_42,
        _column_43,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_23,
        _column_24,
        _column_25,
        _column_44,
        _column_45,
        _column_46,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 localStorytellers = Shape11(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
        _column_10,
        _column_47,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recordingSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxRecordingsProjectRecorded = i1.Index(
    'idx_recordings_project_recorded',
    'CREATE INDEX idx_recordings_project_recorded ON local_recordings (project_id, recorded_at)',
  );
  final i1.Index idxRecordingsStatusRecorded = i1.Index(
    'idx_recordings_status_recorded',
    'CREATE INDEX idx_recordings_status_recorded ON local_recordings (upload_status, recorded_at)',
  );
  final i1.Index idxRecordingsServerId = i1.Index(
    'idx_recordings_server_id',
    'CREATE INDEX idx_recordings_server_id ON local_recordings (server_id)',
  );
  final i1.Index idxRecordingsStorytellerId = i1.Index(
    'idx_recordings_storyteller_id',
    'CREATE INDEX idx_recordings_storyteller_id ON local_recordings (storyteller_id)',
  );
  final i1.Index idxStorytellersProjectId = i1.Index(
    'idx_storytellers_project_id',
    'CREATE INDEX idx_storytellers_project_id ON local_storytellers (project_id)',
  );
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fileSizeBytes =>
      columnsByName['file_size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFilePath =>
      columnsByName['local_file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gcsUrl =>
      columnsByName['gcs_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryGenreId =>
      columnsByName['secondary_genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondarySubcategoryId =>
      columnsByName['secondary_subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryRegisterId =>
      columnsByName['secondary_register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cleaningStatus =>
      columnsByName['cleaning_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastRetryAt =>
      columnsByName['last_retry_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get resumableSessionUri =>
      columnsByName['resumable_session_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uploadedBytes =>
      columnsByName['uploaded_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get md5Hash =>
      columnsByName['md5_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get splitFromId =>
      columnsByName['split_from_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get splitIndex =>
      columnsByName['split_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get splitSegmentCount =>
      columnsByName['split_segment_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reviewFlagsJson =>
      columnsByName['review_flags_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metadataSyncStatus =>
      columnsByName['metadata_sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pendingMetadataJson =>
      columnsByName['pending_metadata_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get metadataRetryCount =>
      columnsByName['metadata_retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get metadataLastRetryAt =>
      columnsByName['metadata_last_retry_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metadata_sync_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'synced\''),
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pending_metadata_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'metadata_retry_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<DateTime> _column_52(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'metadata_last_retry_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );

final class Schema14 extends i0.VersionedSchema {
  Schema14({required super.database}) : super(version: 14);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localRecordings,
    localGenres,
    localSubcategories,
    localStorytellers,
    recordingSessions,
    idxRecordingsProjectRecorded,
    idxRecordingsStatusRecorded,
    idxRecordingsServerId,
    idxRecordingsStorytellerId,
    idxStorytellersProjectId,
  ];
  late final Shape13 localRecordings = Shape13(
    source: i0.VersionedTable(
      entityName: 'local_recordings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_19,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_17,
        _column_41,
        _column_42,
        _column_43,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_23,
        _column_24,
        _column_25,
        _column_44,
        _column_45,
        _column_46,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localGenres = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localSubcategories = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_subcategories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_2, _column_18, _column_19, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 localStorytellers = Shape11(
    source: i0.VersionedTable(
      entityName: 'local_storytellers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_18,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_14,
        _column_33,
        _column_10,
        _column_47,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 recordingSessions = Shape14(
    source: i0.VersionedTable(
      entityName: 'recording_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_17,
        _column_26,
        _column_27,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_53,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxRecordingsProjectRecorded = i1.Index(
    'idx_recordings_project_recorded',
    'CREATE INDEX idx_recordings_project_recorded ON local_recordings (project_id, recorded_at)',
  );
  final i1.Index idxRecordingsStatusRecorded = i1.Index(
    'idx_recordings_status_recorded',
    'CREATE INDEX idx_recordings_status_recorded ON local_recordings (upload_status, recorded_at)',
  );
  final i1.Index idxRecordingsServerId = i1.Index(
    'idx_recordings_server_id',
    'CREATE INDEX idx_recordings_server_id ON local_recordings (server_id)',
  );
  final i1.Index idxRecordingsStorytellerId = i1.Index(
    'idx_recordings_storyteller_id',
    'CREATE INDEX idx_recordings_storyteller_id ON local_recordings (storyteller_id)',
  );
  final i1.Index idxStorytellersProjectId = i1.Index(
    'idx_storytellers_project_id',
    'CREATE INDEX idx_storytellers_project_id ON local_storytellers (project_id)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subcategoryId =>
      columnsByName['subcategory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get registerId =>
      columnsByName['register_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storytellerId =>
      columnsByName['storyteller_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastCheckpointAt =>
      columnsByName['last_checkpoint_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalDurationSeconds =>
      columnsByName['total_duration_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get segmentPathsJson =>
      columnsByName['segment_paths_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isPaused =>
      columnsByName['is_paused']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get lastSegmentIndex =>
      columnsByName['last_segment_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get finalizedAudioPath =>
      columnsByName['finalized_audio_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get finalizedDurationSeconds =>
      columnsByName['finalized_duration_seconds']!
          as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'finalized_audio_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_54(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'finalized_duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
  required Future<void> Function(i1.Migrator m, Schema14 schema) from13To14,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      case 10:
        final schema = Schema11(database: database);
        final migrator = i1.Migrator(database, schema);
        await from10To11(migrator, schema);
        return 11;
      case 11:
        final schema = Schema12(database: database);
        final migrator = i1.Migrator(database, schema);
        await from11To12(migrator, schema);
        return 12;
      case 12:
        final schema = Schema13(database: database);
        final migrator = i1.Migrator(database, schema);
        await from12To13(migrator, schema);
        return 13;
      case 13:
        final schema = Schema14(database: database);
        final migrator = i1.Migrator(database, schema);
        await from13To14(migrator, schema);
        return 14;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
  required Future<void> Function(i1.Migrator m, Schema14 schema) from13To14,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
    from8To9: from8To9,
    from9To10: from9To10,
    from10To11: from10To11,
    from11To12: from11To12,
    from12To13: from12To13,
    from13To14: from13To14,
  ),
);
