FROM nginx:alpine

RUN apk add --no-cache curl && \
    curl -sL -o /tmp/sql-wasm.wasm https://cdn.jsdelivr.net/npm/sql.js@1.11.0/dist/sql-wasm.wasm

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY build/web /usr/share/nginx/html
RUN cp /tmp/sql-wasm.wasm /usr/share/nginx/html/sql-wasm.wasm

EXPOSE 8080
